### PR TITLE
Fix for bamboo branch name, match push_helpers.rb functionality

### PR DESCRIPTION
**Pull request by kvarga**
Fix Related to #1011

### CODE REVIEW

**Comment by kvarga** [comment]
Thoughts @kdaigle ? I am wondering if we can fix our issue with using / in branchnames with this fix, if not, I need to start working on other alternatives.

**Comment by kdaigle** [comment]
@kvarga any chance you could add a test case showing that this fixes the problem in 1011?

**Comment by kvarga** [comment]
I took a look at it before, and I made a test case with the following code:

```Ruby
def test_branch_with_slash
    self.data.update('build_key' => 'test/test')
    self.payload.update('ref' => 'test/test')
    @stubs.post "/rest/api/latest/queue/ABC" do |env|
      valid_response("ABC")
    end

    svc = service :push, data, payload
    svc.receive
    print svc

    @stubs.verify_stubbed_calls
end
```

However, this seems to succeed with and without my fix. I'm not familiar enough with Ruby or github-services to figure out next steps so that it would assert an error. Ideally I would be able to update test_bamboo.rb and run against HEAD and have an error, merge my fix in bamboo.rb in, and re-run tests and verify.

With this update (which I have not commit/pushed), the tests pass either way which does not seem ideal. Any pointers?

**Comment by kvarga** [comment]
@kdaigle After some playing around and looking at other tests I was able to add a test that failed before the change and works now.

**Comment by kdaigle** [comment]
@kvarga awesome! Sorry for the delay in getting back to you but thanks for tackling this. I'll review this today or tomorrow and get it :ship: for you.

**Comment by kvarga** [comment]
Have you had a chance to look at this @kdaigle ? Thanks

**Comment by kdaigle** [comment]
Thanks for the tests and the fix! :cake: This will go out later today.

**Pull request merged**
