### PR TITLE
Receive pull requests as well as issues, and add test for it

### PR DESCRIPTION
**Pull request by calexicoz**

### CODE REVIEW

**Comment by calexicoz** [comment]
Hi, any update on this? Thanks!

**Comment by kdaigle** [comment]
Hey @calexicoz! We only generally review things once a week so sorry for the delay on this.

I'll merge this in. Just so you know, existing services won't be updated with the new events you're adding here. Services get "locked" to the events the service has when that service is installed. If a user removes the service and re-adds it, they would be able to get the new events you want. (If you used webhooks via OAuth and the API, your app could control what events are used.)

**Comment by calexicoz** [comment]
Great. Thanks for letting me know. I'll update the services I have access to on my side.

And thanks for merging this :)

**Comment by kdaigle** [comment]
This will go live later today. :cake:

**Pull request merged**
