### PR TITLE
Updated text for IDS Bluemix rebranding

### PR DESCRIPTION
**Pull request by ibmdevops**
Updated documentation and service title for IDS Bluemix rebranding along with merges.

### CODE REVIEW

**Comment by idsdev** [comment]
Any update on this pull request?

**Comment by kdaigle** [comment]
Thanks! :cake: This will go out sometime today.

**Comment by ibmdevops** [comment]
@kdaigle Thanks!  When can we expect these changes to go live?  I've just checked and the documentation and service title have not yet been updated.

**Comment by kdaigle** [comment]
It's live now!

**Comment by ibmdevops** [comment]
@kdaigle Excellent! Thanks very much.

**Pull request merged**
