### PR TITLE
Add ability to send XMPP IMs from github via hook

### PR DESCRIPTION
**Pull request by lloydwatkin**
This pull requests adds a standard XMPP instant message service to Github. The reason this is done via a separate service rather than combined with the XMPP MUC one is that users choose to join a multi-user chat and so firing a large number of hooks at it isn't a problem. With this service messages are pushed to a user directly and therefore they may want to only be informed about a smaller number of events (e.g. issues/pull requests/comments).

I've moved all of the shared code out to a base class which is extended by both this service and the MUC one to save duplication of code.

### CODE REVIEW

**Comment by kdaigle** [comment]
@lloydwatkin do you want to coordinate when this goes live so you can test it? As always, I defer to you on these XMPP changes.

**Comment by lloydwatkin** [comment]
Sure, suggest some times/dates and I'll let you know if something doesn't work. Given the working MUC plugin I perceive very little issues with this.

**Comment by kdaigle** [comment]
Give you weren't too worried about this, I merged it. :grinning: It'll go out later today. :cake:

**Comment by lloydwatkin** [comment]
:+1:

**Comment by kdaigle** [comment]
@lloydwatkin this is live! Let me know if we need to follow-up with any bug fixes.

**Comment by lloydwatkin** [comment]
@kdaigle tested and its working great! Thanks!

The only think that I now note is that the XMPP MUC plugin is reporting itself as 'XmppHelper'. The standard IM plugin is fine.

**Pull request merged**
