### PR TITLE
Push commit info to JIRA as comment

### PR DESCRIPTION
**Pull request by elordahl**
Having commit information posted directly to a JIRA ticket is extremely convenient.  

These changes will enable GitHub to push the author, commit message, commit-url, and changed files directly to the JIRA ticket specified in the commit message.  It does so by creating a comment as the user specified in the service configuration.

I made these changes without modifying any of the existing functionality, but have added myself as a maintainer with hope of improving this plugin.  I've also added the URL to the logo.

### CODE REVIEW

**Comment by kdaigle** [comment]
@elordahl thanks for these updates! Could you add some tests to show that the changes you've made won't break and ensure none of the changes you've made break existing functionality? :sparkles:

**Comment by kdaigle** [comment]
@elordahl hoping that you or someone else in the community familiar with JIRA can add some tests for this.

**Comment by elordahl** [comment]
I will add some tests.  We're using a local node server to perform these tasks w/ web hooks now.  I need to make a few modifications, including handling of distinct commits.

**Comment by kdaigle** [comment]
@elordahl just wanted to check in with you and see if you made any progress with tests and distinct commit changes. :grinning:

**Comment by elordahl** [comment]
@kdaigle I'm sorry it slipped my mind (for three months).  I will try to work this week on pushing my updates here.

**Comment by elordahl** [comment]
Tomorrow, I'll do some more thorough testing and add some test cases.

**Comment by kdaigle** [comment]
@elordahl any chance you can add the tests? :grinning: Otherwise, we'll close this PR and you can re-open it once you're ready to go. :cake:

**Comment by elordahl** [comment]
Feel free to close it, and I can reopen it in the near future.  I won't be
able to add the tests unt after June 19th. :(

Thanks,
Eric

**Comment by elordahl** [comment]
@kdaigle Is there any documentation on how to best use these tests?  Most of the services i've viewed seem to instantiate services with dummy values, and then perform some basic assertion operation against them.  It doesn't seem like it's _really_ doing anything :grimacing:

**Comment by kdaigle** [comment]
The main goal of the tests are to ensure that, given a certain payload from GitHub, you service receives the `POST` it's expecting. The tests can look pretty odd given all the stubbing but that's the ultimate goal. :grinning:

**Pull request closed without merging**
