### PR TITLE
Remove CircleCI from Service Hooks integration

### PR DESCRIPTION
**Pull request by zzak**
There was a time when we first migrated to the Webhooks API,
long ago, that we still accepted callbacks from hooks setup here.

We have since stopped accepting these hooks.

This is because there is no way to properly sign them here.

So the hooks the only way to use our service is with a signed hook which we created.

This has lead to some confusion, by users who accidentally delete our hook,
and try to recreate the hook themselves using this service.

We'd like to avoid support requests for these old hooks.

Please note: GitHub will only accept pull requests to existing services that implement bug fixes or security improvements. We no longer accept feature changes to existing services.

### CODE REVIEW

**Comment by kdaigle** [comment]
@zzak we don't currently have a way to remove a service that doesn't also remove all installations of that service. Presumably, you'd like things to continue to work for anyone who is currently using the CircleCI service?

**Comment by zzak** [comment]
Hello @kdaigle,

Thanks for your reply!

If by removing all installations of the service, you mean the service hooks from this screen?

screenshot from 2017-04-27 15-29-35

Then I think that is OK, since we won't accept any requests sent via this webhook. Unless the hook is created on our end through the Webhooks API, where we can sign it, then we won't accept it.

Does that make sense?

Thank you for expressing caution in this :)

**Comment by drazisil** [comment]
@kdaigle Yes, it is ok to remove all instances of this from repositories as well. Since we use web hooks, all instances of it are broken and therefore cause confusion.

**Comment by gjtorikian** [comment]
Sorry for the delay in this. I'll be merging, deploying, and removing this service from existing repositories.

**Comment by drazisil** [comment]
@gjtorikian Thank you very much!

**Comment by zzak** [comment]
@gjtorikian Thank you!! :bow:

**Comment by gjtorikian** [comment]
No worries. I'll update this thread when it's live across the many servers of GitHub (later today, for sure).

**Comment by gjtorikian** [comment]
This is now gone, gone, gone.

**Pull request merged**
