### PR TITLE
Remove unused services.

### PR DESCRIPTION
**Pull request by mikemcquaid**
These seem currently unused by any GitHub users so should be removed.

### CODE REVIEW

**Comment by bswinnerton** [comment]
Looks like all of the associated `docs/*` files have been removed. 👍 .

**Comment by mikemcquaid** [comment]
@bswinnerton Or they were never there which is why they were never installed, perhaps.

**Comment by bswinnerton** [comment]
It looks like (at least) `/docs/basecamp_classic` was added in fddd20c, but later removed in 7749de1. But yes, you're probably right, that might explain why some of these services were never installed 😄.

After doing a little more digging, it looks like [`docs/nma`](https://github.com/github/github-services/blob/81864a39bc318f6c8a4f359ad1f40239e3f95e24/docs/nma) is associated to the `lib/services/notifymyandroid.rb` file that was removed in this pull request. We'll probably want to remove that as well.

**Comment by mikemcquaid** [comment]
This was my mistake with some confusion with the underlying data; these are all still installed and used.

**Pull request closed without merging**
