### PR TITLE
Update teamcity

### PR DESCRIPTION
**Pull request by Julia-Alexandrova**
Please note: GitHub will only accept pull requests to existing services that implement bug fixes or security improvements. We no longer accept feature changes to existing services.

### CODE REVIEW

**Comment by izuzak** [comment]
Hi @Julia-Alexandrova 👋 

Can you share a link to some documentation which clearly states that using that plugin is recommended for versions 10.0 and above? The page you linked to in the pull request doesn't say that.

Thanks!

**Comment by VladRassokhin** [comment]
@izuzak [Here's our (TeamCity team, published by Julia) plog post](https://blog.jetbrains.com/teamcity/2016/09/installing-github-webhooks-from-teamcity/) about that feature. There's no clear statement that that approach is better in public, but it's our intention.

**Comment by izuzak** [comment]
Thanks for clarifying, @VladRassokhin 🙇

**Comment by VladRassokhin** [comment]
Ok. Thanks, Ivan.

**Pull request merged**
